name: build

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  workflow_dispatch:
    
  schedule:
    - cron: '22 06 * * *'   # once a day @ 6:22am UTC

env:
  SCHEME: "SwiftUITokenField-CI"

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify && exit ${PIPESTATUS[0]}
    - name: Unit Tests
      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=macOS" | xcbeautify && exit ${PIPESTATUS[0]}
  
  macCatalyst:
    name: macCatalyst
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac" | xcbeautify && exit ${PIPESTATUS[0]}
    - name: Unit Tests
      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify && exit ${PIPESTATUS[0]}
  
  examples:
    name: Examples
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: TokenField Enum - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/TokenField Enum/TokenField Enum.xcodeproj" -resolvePackageDependencies | xcbeautify && exit ${PIPESTATUS[0]}
    - name: TokenField Enum - Build
      run: xcodebuild build -project "Examples/TokenField Enum/TokenField Enum.xcodeproj" -scheme "TokenField Enum" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify && exit ${PIPESTATUS[0]}
    
    - name: TokenField String - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/TokenField String/TokenField String.xcodeproj" -resolvePackageDependencies | xcbeautify && exit ${PIPESTATUS[0]}
    - name: TokenField String - Build
      run: xcodebuild build -project "Examples/TokenField String/TokenField String.xcodeproj" -scheme "TokenField String" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify && exit ${PIPESTATUS[0]}
    
    - name: TokenTextField Enum - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/TokenTextField Enum/TokenTextField Enum.xcodeproj" -resolvePackageDependencies | xcbeautify && exit ${PIPESTATUS[0]}
    - name: TokenTextField Enum - Build
      run: xcodebuild build -project "Examples/TokenTextField Enum/TokenTextField Enum.xcodeproj" -scheme "TokenTextField Enum" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify && exit ${PIPESTATUS[0]}
    
    - name: TokenTextField String - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/TokenTextField String/TokenTextField String.xcodeproj" -resolvePackageDependencies | xcbeautify && exit ${PIPESTATUS[0]}
    - name: TokenTextField String - Build
      run: xcodebuild build -project "Examples/TokenTextField String/TokenTextField String.xcodeproj" -scheme "TokenTextField String" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify && exit ${PIPESTATUS[0]}
